# Como Minikube não suporta LoadBalancer por padrão, configure o serviço como ClusterIP e habilite o Ingress para expor o SonarQube.
# values.yaml

service:
  type: ClusterIP

ingress:
  enabled: true
  hosts:
    - host: sonarqube.local
      paths:
        - /

postgresql:
  enabled: true
  postgresqlUsername: sonarqube
  postgresqlPassword: sonarqube_password
  postgresqlDatabase: sonarqube
  persistence:
    enabled: true
    size: 3Gi

persistence:
  enabled: true
  size: 3Gi

resources:
  requests:
    memory: "2Gi"
    cpu: "1000m"
  limits:
    memory: "4Gi"
    cpu: "2000m"
